/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

import javax.swing.JOptionPane;

/**
 *
 * @author win-8
 */
public class Aboutus extends javax.swing.JFrame {

    /**
     * Creates new form Aboutus
     */
    public Aboutus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Minimize = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        doctorportal = new javax.swing.JLabel();
        patientportal = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        database = new javax.swing.JLabel();
        Bugfixer = new javax.swing.JLabel();
        Design = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        doctorportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctorportal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorportalMouseClicked(evt);
            }
        });
        getContentPane().add(doctorportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 230, 30));

        patientportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientportal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientportalMouseClicked(evt);
            }
        });
        getContentPane().add(patientportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 240, 30));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 30));

        database.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        database.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databaseMouseClicked(evt);
            }
        });
        database.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                databaseKeyPressed(evt);
            }
        });
        getContentPane().add(database, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 230, 20));

        Bugfixer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bugfixer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BugfixerMouseClicked(evt);
            }
        });
        Bugfixer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BugfixerKeyPressed(evt);
            }
        });
        getContentPane().add(Bugfixer, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 130, 20));

        Design.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Design.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesignMouseClicked(evt);
            }
        });
        Design.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DesignKeyPressed(evt);
            }
        });
        getContentPane().add(Design, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 200, 20));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/ABOUT_US.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);           // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void patientportalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientportalMouseClicked
patientlogin ob = new patientlogin();
this.setVisible(false);
ob.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_patientportalMouseClicked

    private void doctorportalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorportalMouseClicked
doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_doctorportalMouseClicked

    private void BugfixerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BugfixerKeyPressed
     JOptionPane.showMessageDialog(this, "Tries to make the software run smoothly and handles all bugs.");   // TODO add your handling code here:
    }//GEN-LAST:event_BugfixerKeyPressed

    private void databaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_databaseKeyPressed
       JOptionPane.showMessageDialog(this, "The DON. Handles the backend with all his databases, queries and programming skills"); // TODO add your handling code here:
    }//GEN-LAST:event_databaseKeyPressed

    private void DesignKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DesignKeyPressed
     JOptionPane.showMessageDialog(this, "Make awesome designs to make user interface admirable");   // TODO add your handling code here:
    }//GEN-LAST:event_DesignKeyPressed

    private void databaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databaseMouseClicked
        JOptionPane.showMessageDialog(this, "The DON. Handles the backend with all his databases, queries and programming skills"); // TODO add your handling code here:
    }//GEN-LAST:event_databaseMouseClicked

    private void BugfixerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BugfixerMouseClicked
        JOptionPane.showMessageDialog(this, "Tries to make the software run smoothly and handle all the bugs."); // TODO add your handling code here:
    }//GEN-LAST:event_BugfixerMouseClicked

    private void DesignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesignMouseClicked
         JOptionPane.showMessageDialog(this, "Make awesome designs to make user interface admirable");// TODO add your handling code here:
    }//GEN-LAST:event_DesignMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aboutus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aboutus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aboutus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aboutus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aboutus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Bugfixer;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Design;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel database;
    private javax.swing.JLabel doctorportal;
    private javax.swing.JLabel patientportal;
    // End of variables declaration//GEN-END:variables
}
