/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

/**
 *
 * @author win-8
 */
public class bmipredicted extends javax.swing.JFrame {

    /**
     * Creates new form bmipredicted
     */
    public bmipredicted() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bmifinal = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        doctorsportal = new javax.swing.JLabel();
        Patientsportal = new javax.swing.JLabel();
        Aboutus = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bmifinal.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        getContentPane().add(bmifinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 410, 50));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        doctorsportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctorsportal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorsportalMouseClicked(evt);
            }
        });
        getContentPane().add(doctorsportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 230, 30));

        Patientsportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Patientsportal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientsportalMouseClicked(evt);
            }
        });
        getContentPane().add(Patientsportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 240, 30));

        Aboutus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusMouseClicked(evt);
            }
        });
        getContentPane().add(Aboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, 130, 30));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 30));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/bmi2.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void PatientsportalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientsportalMouseClicked
patientlogin ob = new patientlogin();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_PatientsportalMouseClicked

    private void doctorsportalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsportalMouseClicked
      doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);   // TODO add your handling code here:
        // TODO add your handling code here        // TODO add your handling code here:
    }//GEN-LAST:event_doctorsportalMouseClicked

    private void AboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusMouseClicked
Aboutus ob = new Aboutus();
this.setVisible(false);
ob.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_AboutusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bmipredicted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bmipredicted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bmipredicted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bmipredicted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bmipredicted().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutus;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Patientsportal;
    public javax.swing.JLabel bmifinal;
    private javax.swing.JLabel doctorsportal;
    // End of variables declaration//GEN-END:variables
}
