/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

/**
 *
 * @author win-8
 */
public class Diseasedata extends javax.swing.JFrame {

    /**
     * Creates new form Diseasedata
     */
    public Diseasedata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Disease = new javax.swing.JComboBox<>();
        Tick = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Notification = new javax.swing.JLabel();
        patient_message = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Disease.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Disease.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malaria", "Dengue", "Smallpox", "Tuberculosis", "Cholera", "Typhoid", "Swine Flu", "Amebiasis", "AIDS", "Ebola" }));
        Disease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiseaseActionPerformed(evt);
            }
        });
        getContentPane().add(Disease, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 150, -1));

        Tick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TickMouseClicked(evt);
            }
        });
        getContentPane().add(Tick, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, 70, 60));

        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 190, 70, 20));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 30));

        Notification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Notification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NotificationMouseClicked(evt);
            }
        });
        getContentPane().add(Notification, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 200, 30));

        patient_message.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patient_message.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient_messageMouseClicked(evt);
            }
        });
        getContentPane().add(patient_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 290, 30));

        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 110, 20));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/doctor-disease.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiseaseActionPerformed


// TODO add your handling code here:
    }//GEN-LAST:event_DiseaseActionPerformed

    private void TickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TickMouseClicked
int a = Disease.getSelectedIndex();  
String dis[] = new String[10];
dis[0]="malaria";
dis[1]="dengue";
dis[2]="smallpox";
dis[3]="tuberculosis";
dis[4]="cholera";
dis[5]="typhoid";
dis[6]="swineflu";
dis[7]="amebiasis";
dis[8]="aids";
dis[9]="ebola";
String ans = dis[a];
String pass[] = new String[1];
pass[0] = ans;
this.setVisible(false);
Diseasedataprint.main(pass);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_TickMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked

    private void NotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificationMouseClicked
Notification ob = new Notification();
this.setVisible(false);
ob.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_NotificationMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
    Docprofile ob = new Docprofile();
this.setVisible(false);
ob.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_profileMouseClicked

    private void patient_messageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_messageMouseClicked
     Docmessage ob = new Docmessage();
this.setVisible(false);
ob.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_patient_messageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diseasedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diseasedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diseasedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diseasedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diseasedata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Close;
    private javax.swing.JComboBox<String> Disease;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Notification;
    private javax.swing.JLabel Tick;
    private javax.swing.JLabel patient_message;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
