/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

import static air.med.Patientsignup.isValidEmailAddress;
//import static air.med.Patientsignup.usr;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author win-8
 */
public class doctorsiup extends javax.swing.JFrame {
public static String usr = null;
    /**
     * Creates new form doctorsiup
     */
    public doctorsiup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Minimize = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Next = new javax.swing.JLabel();
        Aboutus = new javax.swing.JLabel();
        patientp = new javax.swing.JLabel();
        doctorp = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 250, 30));

        jTextField2.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 250, 30));

        jTextField3.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 250, 30));

        jTextField4.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 250, 30));

        jTextField5.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 250, 30));

        jTextField6.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 250, 30));

        jTextField7.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 250, 30));

        Group.add(Male);
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 717, -1, -1));

        Group.add(Female);
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 717, 20, -1));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 30, 40));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 30, 40));

        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 690, 140, 70));

        Aboutus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusMouseClicked(evt);
            }
        });
        getContentPane().add(Aboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 90, 130, 30));

        patientp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientpMouseClicked(evt);
            }
        });
        getContentPane().add(patientp, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 240, 30));

        doctorp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctorp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorpMouseClicked(evt);
            }
        });
        getContentPane().add(doctorp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 240, 30));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, 30));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, 250, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allergist", "Cardiologist", "Dentist", "Dermatologist", "Microbiologist", "Neurologist", "Nephrologist", "Pediatrician", "Psychiatrist", " ", " ", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, 250, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/DOCTORSIGNUP.jpg"))); // NOI18N
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked
Connection con = null;
    Statement st = null;
    //Statement st1 = null;
    ResultSet rs = null;
    String s;
    
    String pass = null;
    String gp = null;
    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked
   
     
       
      
      
      char[] password = jPasswordField1.getPassword();
      pass = new String(password);
      int count = 0;
      int counter = 0;
      if(jTextField1.getText().length()==0||jTextField2.getText().length()==0||jTextField3.getText().length()==0||jTextField4.getText().length()==0||jTextField5.getText().length()==0||jTextField6.getText().length()==0||jTextField7.getText().length()==0)
            {
                JOptionPane.showMessageDialog(this, "Necessary fields are empty");
                return;
            }
         if(pass.length()==0)
         {
         JOptionPane.showMessageDialog(this, "Empty password field");
         return;
         }
          if(Male.isSelected()==false && Female.isSelected()==false){
              JOptionPane.showMessageDialog(this, "Please select your gender");
              return;}

if(jTextField7.getText().length()!=10){
              JOptionPane.showMessageDialog(this, "Please enter a valid 10 digit phone number");
              return;}
          if(jTextField6.getText().length()!=6){
              JOptionPane.showMessageDialog(this, "Please enter a valid 6 digit pincode");
              return;}
          String emailcheck = jTextField3.getText();
          boolean  a = isValidEmailAddress(emailcheck);
          if(a==false)
          {
              JOptionPane.showMessageDialog(this, "Please enter a valid e-mail address");
              return;}
        if(Male.isSelected())
            count=1;
        
        
         int category = jComboBox1.getSelectedIndex();  
String dis[] = new String[9];
dis[0]="Allergist";
dis[1]="Cardiologist";
dis[2]="Dentist";
dis[3]="Dermatologist";
dis[4]="Microbiologist";
dis[5]="Neurologist";
dis[6]="Nephrologist";
dis[7]="Pediatrician";
dis[8]="Psychiatrist";
String specialization = dis[category];

usr = jTextField2.getText();
        usr = usr.trim();
        String name = jTextField1.getText();
        name = name.trim();
        String email = jTextField3.getText();
        email = email.trim();
        String city = jTextField4.getText();
        city = city.trim();
        String state = jTextField5.getText();
        state = state.trim();
        String pin = jTextField6.getText();
        pin = pin.trim();
        String phoneno = jTextField7.getText();
        phoneno = phoneno.trim();
        int pincode = 0;



 try
        {
        pincode = Integer.parseInt(pin);
        //phone = Integer.parseInt(phoneno);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Pincode should be a numerical value");
            return;
        }
         for(int i = 0;i<phoneno.length();i++)
         {
             if(Character.isDigit(phoneno.charAt(i))==false)
             {
             JOptionPane.showMessageDialog(this, "Phone number should be a numerical value");
             return;
         }
         }
         
         try {
            gp = AESCrypt.encrypt(pass);
        } catch (Exception ex) {
            Logger.getLogger(patientlogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airmed?useSSL=false","root", "aman");
            Statement stmt = con.createStatement();
            Statement stmt1 = con.createStatement();
            String stm = "SELECT COUNT(*) AS total from airmed.doc_id WHERE Doc_ID = '" + usr + "'";
            ResultSet rs1 = stmt.executeQuery(stm);
    while(rs1.next()){
    counter = rs1.getInt("total");
    }
    if(counter==0)
    {
        JOptionPane.showMessageDialog(this, "This Doctor ID is not found in our database!");
        return;
    }
    
   
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airmed?useSSL=false","root", "aman");
            Statement stmt6 = con.createStatement();
            Statement stmt7 = con.createStatement();
            String st = "SELECT COUNT(*) AS total from airmed.dlogin WHERE doc_ID = '" + usr + "'";
            ResultSet rs6 = stmt7.executeQuery(st);
    while(rs6.next()){
    counter = rs6.getInt("total");
    }
    if(counter>0)
    {
        JOptionPane.showMessageDialog(this, "Doctor_ID has already signed up already exists...");
        return;
    }
    
    String sql = "insert into dlogin values('"+usr+"','"+gp+"');";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Congratulations!!\nYou are successfully registered!!");
            String insert = "INSERT INTO airmed.doctordetails VALUES('"+usr+"','"+name+"','"+email+"','"+city+"','"+state+"','"+pincode+"','"+phoneno+"','"+specialization+"','"+count+"');";
stmt1.executeUpdate(insert);
    






String table = "doc"+usr;
String sqll = "CREATE TABLE "+table+
                   "(doc_id VARCHAR(45) not NULL, " +
                   " Name_of_patient VARCHAR(45), " + 
                   " patient_id VARCHAR(45), " +  
                   " Date VARCHAR(45), " + " Problem VARCHAR(2000))"; 
                   

stmt.executeUpdate(sqll);

    
    
    doctorone ob = new doctorone();
            this.setVisible(false);
            ob.setVisible(true);
    
    
    
        }
catch (SQLException ex) {
            Logger.getLogger(patientlogin.class.getName()).log(Level.SEVERE, null, ex);
        }  //count query to check if it exists


















// TODO add your handling code here:
    }//GEN-LAST:event_NextMouseClicked

    private void AboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusMouseClicked
Aboutus ob = new Aboutus();
this.setVisible(false);
ob.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_AboutusMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
    Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void patientpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientpMouseClicked
patientlogin ob = new patientlogin();
this.setVisible(false);
ob.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_patientpMouseClicked

    private void doctorpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorpMouseClicked
doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_doctorpMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed



         


// TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorsiup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorsiup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorsiup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorsiup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctorsiup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutus;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Close;
    private javax.swing.JRadioButton Female;
    private javax.swing.ButtonGroup Group;
    private javax.swing.JLabel Home;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Next;
    private javax.swing.JLabel doctorp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPasswordField jPasswordField1;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel patientp;
    // End of variables declaration//GEN-END:variables
}
