/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

//import static air.med.patientlogin.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;



/**
 *
 * @author win-8
 */
public class doctorone extends javax.swing.JFrame {
    public static String docname = "";
    public static String naam = "";
    public static String specialization = "";
    public static String City = "";
    public static String State = "";
    public static String Pin = "";
    public static String Phone = "";
    /**
     * Creates new form doctorone
     */
    public doctorone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorid = new javax.swing.JTextField();
        Close = new javax.swing.JLabel();
        aboutus = new javax.swing.JLabel();
        doctorsportal = new javax.swing.JLabel();
        docsignup = new javax.swing.JLabel();
        Patientsportal = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Forget = new javax.swing.JLabel();
        docpass = new javax.swing.JPasswordField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorid.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(doctorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 220, -1));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        aboutus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
        });
        getContentPane().add(aboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, 130, 30));

        doctorsportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(doctorsportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 240, 30));

        docsignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        docsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docsignupMouseClicked(evt);
            }
        });
        getContentPane().add(docsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 330, 30));

        Patientsportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Patientsportal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientsportalMouseClicked(evt);
            }
        });
        getContentPane().add(Patientsportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 94, 240, 30));

        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 160, 50));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 94, 90, 30));

        Forget.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Forget.setForeground(new java.awt.Color(0, 51, 255));
        Forget.setText("Forgot Password?");
        Forget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetMouseClicked(evt);
            }
        });
        getContentPane().add(Forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 160, 20));
        getContentPane().add(docpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 220, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/DOCTORLOGIN.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void PatientsportalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientsportalMouseClicked
patientlogin ob = new patientlogin();
this.setVisible(false);
ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_PatientsportalMouseClicked

    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
Aboutus ob = new Aboutus();
this.setVisible(false);
ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_aboutusMouseClicked
Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        String s;
   
    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
try {
          docname = doctorid.getText();
          char[] pa = docpass.getPassword();
          String password = new String(pa);
          if(docname.length()==0||password.length()==0)
        {
            //JOptionPane.showMessageDialog(this, "Necessary fields are left empty/nPlease re-enter.");
            //return;
            JOptionPane.showMessageDialog(this, "Necessary fields are left empty\nPlease re-enter.", "Warning...",
        JOptionPane.WARNING_MESSAGE);
            return;
        }
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airmed?useSSL=false","root", "aman");
            Statement stmt = con.createStatement();
            
            
            
                  String stm = "SELECT COUNT(*) AS total from airmed.dlogin WHERE doc_ID = '" + docname + "'";
    
            ResultSet rs1;
            int counter = 0;
    try {
        Statement stmt1=con.createStatement();
        rs1 = stmt1.executeQuery(stm);
        while(rs1.next()){
    counter = rs1.getInt("total");
    }
    } catch (SQLException ex) {
        Logger.getLogger(Forgetpatient.class.getName()).log(Level.SEVERE, null, ex);
    }
    if(counter==0)
    {
        JOptionPane.showMessageDialog(this, "Doctor doesn't exist...");
        doctorid.setText("");
        docpass.setText("");
        return;
    }
       
            
            
            
            //String sql = "insert into login values('"+usr+"','"+gp+"');";
            //stmt.executeUpdate(sql);
            ResultSet rs = stmt.executeQuery("Select doc_Password from dlogin where doc_ID = '"+docname+"';");
            while(rs.next())
            {
               String dp = AESCrypt.decrypt(rs.getString("doc_Password"));
               if(dp.equals(password))
               {
                  
                  
                  Statement stmt3 = con.createStatement();
        ResultSet rs5;
        //String naam = "";
        //System.out.println(username);
         rs5 = stmt3.executeQuery("Select Name from airmed.doctordetails where doc_ID = '"+docname+"';");
        while(rs5.next())
            {
               naam  = rs5.getString("Name");
            }
        //System.out.println(naam);
        //ob.Name.setText(naam);
        ResultSet rs6 = stmt3.executeQuery("Select Specialization from airmed.doctordetails where doc_ID = '"+docname+"';");
        while(rs6.next())
            {
               specialization  = rs6.getString("Specialization");
            }
        
        ResultSet rs7 = stmt3.executeQuery("Select City from airmed.doctordetails where doc_ID = '"+docname+"';");
        while(rs7.next())
            {
               City  = rs7.getString("City");
            }
        
        ResultSet rs8 = stmt3.executeQuery("Select State from airmed.doctordetails where doc_ID = '"+docname+"';");
        while(rs8.next())
            {
               State  = rs8.getString("State");
            }
        
        ResultSet rs9 = stmt3.executeQuery("Select Pin from airmed.doctordetails where doc_ID = '"+docname+"';");
        while(rs9.next())
            {
               Pin  = rs9.getString("Pin");
            }
        
        ResultSet rs10 = stmt3.executeQuery("Select Phone from airmed.doctordetails where doc_ID = '"+docname+"';");
        while(rs10.next())
            {
               Phone  = rs10.getString("Phone");
            }
        
        
           
                  
                  
                  
                  doctor1 ob = new doctor1();
                  this.setVisible(false);
                  ob.setVisible(true);
//View main menu  
return;
               }
               
            }
            //JOptionPane.showMessageDialog(this, "Incorrect ID or Password\nPlease re-enter");
            JOptionPane optionPane = new JOptionPane("Error Message", JOptionPane.ERROR_MESSAGE);    
JDialog dialog = optionPane.createDialog("Doctor ID or password is incorrect!");
dialog.setAlwaysOnTop(true);
dialog.setVisible(true);
return;

        } catch (SQLException ex) {
            Logger.getLogger(patientlogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(patientlogin.class.getName()).log(Level.SEVERE, null, ex);
        }          // TODO add your handling code here:
              
// TODO add your handling code here:
    }//GEN-LAST:event_LoginMouseClicked

    private void docsignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docsignupMouseClicked
      doctorsiup ob = new doctorsiup();
this.setVisible(false);
ob.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_docsignupMouseClicked

    private void ForgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetMouseClicked
ForgetDoctor ob = new ForgetDoctor();
this.setVisible(false);
ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ForgetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctorone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Forget;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Patientsportal;
    private javax.swing.JLabel aboutus;
    private javax.swing.JPasswordField docpass;
    private javax.swing.JLabel docsignup;
    private javax.swing.JTextField doctorid;
    private javax.swing.JLabel doctorsportal;
    // End of variables declaration//GEN-END:variables
}
