/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

import static air.med.Forgetpatient.id;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author win-8
 */
public class ForgetDoctor extends javax.swing.JFrame {
    public static String id = "";
    /**
     * Creates new form ForgetDoctor
     */
    public ForgetDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        String s;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Submit = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        About_us = new javax.swing.JLabel();
        pp = new javax.swing.JLabel();
        dp = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 80, 80));

        ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 240, -1));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        About_us.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        About_us.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                About_usMouseClicked(evt);
            }
        });
        getContentPane().add(About_us, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, 130, 30));

        pp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppMouseClicked(evt);
            }
        });
        getContentPane().add(pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 240, 30));

        dp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dpMouseClicked(evt);
            }
        });
        getContentPane().add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 230, 30));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/doctorforget.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void About_usMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_About_usMouseClicked
Aboutus ob = new Aboutus();
this.setVisible(false);
ob.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_About_usMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void ppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppMouseClicked
patientlogin ob = new patientlogin();
this.setVisible(false);
ob.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_ppMouseClicked

    private void dpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpMouseClicked
doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_dpMouseClicked

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
   id =  ID.getText();
if(id.length()==0)
{
    JOptionPane.showMessageDialog(this, "Necessary fields are left empty/nPlease re-enter.", "Warning...",
        JOptionPane.WARNING_MESSAGE);
    return;
}
    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airmed?useSSL=false","root", "aman");
    } catch (SQLException ex) {
        Logger.getLogger(Forgetpatient.class.getName()).log(Level.SEVERE, null, ex);
    }
            
    
    String stm = "SELECT COUNT(*) AS total from airmed.dlogin WHERE doc_ID = '" + id + "'";
    
            ResultSet rs1;
            int counter = 0;
    try {
        Statement stmt1=con.createStatement();
        rs1 = stmt1.executeQuery(stm);
        while(rs1.next()){
    counter = rs1.getInt("total");
    }
    } catch (SQLException ex) {
        Logger.getLogger(Forgetpatient.class.getName()).log(Level.SEVERE, null, ex);
    }
    if(counter==0)
    {
        JOptionPane.showMessageDialog(this, "Doctor doesn't exist...");
        ID.setText("");
        return;
    }
    
            //String sql = "insert into login values('"+usr+"','"+gp+"');";
            //stmt.executeUpdate(sql);
            ResultSet rs;
            String E_mail = "";
    try {
        Statement stmt = con.createStatement();
        rs = stmt.executeQuery("Select E_mail from airmed.doctordetails where doc_ID = '"+id+"';");
        while(rs.next())
            {
                E_mail = rs.getString("E_mail");
            }
            }
     catch (SQLException ex) {
        Logger.getLogger(Forgetpatient.class.getName()).log(Level.SEVERE, null, ex);
    }
            String dp = "";
            
            ResultSet rs2;
    try {
        Statement stmt2 = con.createStatement();
        rs2 = stmt2.executeQuery("Select doc_Password from dlogin where doc_ID = '"+id+"';");
         while(rs2.next())
            {
   
        dp = AESCrypt.decrypt(rs2.getString("doc_Password"));
   
            }
    } catch (SQLException ex) {
        Logger.getLogger(Forgetpatient.class.getName()).log(Level.SEVERE, null, ex);
    } catch (Exception ex) {
        Logger.getLogger(Forgetpatient.class.getName()).log(Level.SEVERE, null, ex);
    }
           //System.out.println(E_mail);
           //System.out.println(dp);
           String arg[] = new String[3];
           arg[0] = E_mail;
           String pass = "Your password is "+dp+"\n \n \n \n \n \n Sent by team AIRMED!";
           arg[1] = pass;
           String subject = "Password Recovery";
           arg[2] = subject;
           SendEmail.main(arg);
           if(SendEmail.flag==1)
           {
               JOptionPane.showMessageDialog(this, "Sorry! No internet Connection...");
               return;
           }
           else
           {
                JOptionPane.showMessageDialog(this, "Your password has been sent to your E-mail ID!!");
                patientlogin ob = new patientlogin();
                this.setVisible(false);
                ob.setVisible(true);
           }
// TODO add your handling code here:
                                     
     // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About_us;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Home;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Submit;
    private javax.swing.JLabel dp;
    private javax.swing.JLabel pp;
    // End of variables declaration//GEN-END:variables
}
