/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.year;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import org.jdesktop.swingx.calendar.CalendarUtils;

/**
 *
 * @author win-8
 */
public class Notification extends javax.swing.JFrame {

    /**
     * Creates new form Notification
     */
    public Notification() {
        
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Schedule = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        mtp = new javax.swing.JLabel();
        diseasedata = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        TP = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Schedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheduleMouseClicked(evt);
            }
        });
        getContentPane().add(Schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 414, 230, 70));

        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 200, 70, 10));

        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });
        getContentPane().add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 110, 20));

        mtp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mtpMouseClicked(evt);
            }
        });
        getContentPane().add(mtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 290, 30));

        diseasedata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diseasedata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diseasedataMouseClicked(evt);
            }
        });
        getContentPane().add(diseasedata, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 260, 30));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, 20));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        TP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TP.setForeground(new java.awt.Color(0, 102, 255));
        TP.setText("Treatment Portal");
        TP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPMouseClicked(evt);
            }
        });
        getContentPane().add(TP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/notification.jpg"))); // NOI18N
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleMouseClicked
String a = doctorone.docname;
a="doc"+a;
String ar[]={a};
doctordata.main(ar);
// TODO add your handling code here:
    }//GEN-LAST:event_ScheduleMouseClicked

    private void TPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPMouseClicked
treatment ob = new treatment();
this.setVisible(false);
ob.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_TPMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
Docprofile ob = new Docprofile();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileMouseClicked

    private void mtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtpMouseClicked
Docmessage ob = new Docmessage();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mtpMouseClicked

    private void diseasedataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diseasedataMouseClicked
Diseasedata ob = new Diseasedata();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_diseasedataMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notification().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel Schedule;
    private javax.swing.JLabel TP;
    private javax.swing.JLabel diseasedata;
    private javax.swing.JLabel mtp;
    // End of variables declaration//GEN-END:variables
}
