/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JOptionPane;
/**
 *
 * @author win-8
 */
public class Patientsignup extends javax.swing.JFrame {
   public static String usr = null;
    /**String usr = null;
     * Creates new form Patientsignup
     */
    public Patientsignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        Signup = new javax.swing.JLabel();
        aboutus = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        dp = new javax.swing.JLabel();
        pp = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 280, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 280, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 280, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 280, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 280, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 280, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, 280, -1));

        buttonGroup1.add(Male);
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 647, -1, -1));

        buttonGroup1.add(Female);
        Female.setToolTipText("");
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 650, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 700, 280, 20));

        Signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupMouseClicked(evt);
            }
        });
        getContentPane().add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 680, 110, 50));

        aboutus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
        });
        getContentPane().add(aboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, 130, 30));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        dp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dpMouseClicked(evt);
            }
        });
        getContentPane().add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 230, 30));

        pp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppMouseClicked(evt);
            }
        });
        getContentPane().add(pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 240, 30));

        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/patientSIGNUP.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con = null;
    Statement st = null;
    //Statement st1 = null;
    ResultSet rs = null;
    String s;
    
    String pass = null;
    String gp = null;
    private void SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupMouseClicked
     
         char[] password = jPasswordField1.getPassword();
      pass = new String(password);
      int count = 0;
      int counter = 0;
            if(jTextField1.getText().length()==0||jTextField2.getText().length()==0||jTextField3.getText().length()==0||jTextField4.getText().length()==0||jTextField5.getText().length()==0||jTextField6.getText().length()==0||jTextField7.getText().length()==0)
            {
                JOptionPane.showMessageDialog(this, "Necessary fields are empty");
                return;
            }
         if(pass.length()==0)
         {
         JOptionPane.showMessageDialog(this, "Empty password field");
         return;
         }
          if(Male.isSelected()==false && Female.isSelected()==false){
              JOptionPane.showMessageDialog(this, "Please select your gender");
              return;}
          if(jTextField6.getText().length()!=10){
              JOptionPane.showMessageDialog(this, "Please enter a valid 10 digit phone number");
              return;}
          if(jTextField5.getText().length()!=6){
              JOptionPane.showMessageDialog(this, "Please enter a valid 6 digit pincode");
              return;}
          String emailcheck = jTextField2.getText();
          boolean  a = isValidEmailAddress(emailcheck);
          if(a==false)
          {
              JOptionPane.showMessageDialog(this, "Please enter a valid e-mail address");
              return;}
        if(Male.isSelected())
            count=1;
         if(jTextField1.getText().length()>45||jTextField2.getText().length()>45||jTextField3.getText().length()>=45||jTextField4.getText().length()>45||jTextField5.getText().length()>45||jTextField6.getText().length()>45||jTextField7.getText().length()>45)
            {
                JOptionPane.showMessageDialog(this, "Length of any field should not exceed 45...");
                return;
            }
         
         
        
         
         
         
         
         
       
        usr = jTextField7.getText();
        usr = usr.trim();
       
        String name = jTextField1.getText();
        name = name.trim();
        String email = jTextField2.getText();
        email = email.trim();
        String city = jTextField3.getText();
        city = city.trim();
        String state = jTextField4.getText();
        state = state.trim();
        String pin = jTextField5.getText();
        pin = pin.trim();
        String phoneno = jTextField6.getText();
        phoneno = phoneno.trim();
        int pincode=0;
        try
        {
        pincode = Integer.parseInt(pin);
        //phone = Integer.parseInt(phoneno);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Pincode should be a numerical value");
            return;
        }
         for(int i = 0;i<phoneno.length();i++)
         {
             if(Character.isDigit(phoneno.charAt(i))==false)
             {
             JOptionPane.showMessageDialog(this, "Phone number should be a numerical value");
             return;
         }
         }
         //int phone = Integer.parseInt(phoneno);
            
           
        try {
            gp = AESCrypt.encrypt(pass);
        } catch (Exception ex) {
            Logger.getLogger(patientlogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airmed?useSSL=false","root", "aman");
            Statement stmt = con.createStatement();
            Statement stmt1 = con.createStatement();
            String stm = "SELECT COUNT(*) AS total from airmed.plogin WHERE User_id = '" + usr + "'";
            ResultSet rs1 = stmt.executeQuery(stm);
    while(rs1.next()){
    counter = rs1.getInt("total");
    }
    if(counter>0)
    {
        JOptionPane.showMessageDialog(this, "User already exists...\n Please choose another user name!");
        jTextField7.setText("");
        return;
    }//count query to check if it exists
            

Statement stmt5 = con.createStatement();
String table = "pat"+usr;
      try
      {
      String sqll = "CREATE TABLE "+table+
                   "(User_id VARCHAR(45) not NULL, " +
                   " Name VARCHAR(45), " + 
                   " Doctor VARCHAR(45), " +  
                   " Date VARCHAR(45), " + " Prescription VARCHAR(2000))" ;
                  
stmt.executeUpdate(sqll);
      }
      catch(Exception e)
      {
         JOptionPane.showMessageDialog(this, "Invalid user name!\n Please choose another user name!");
        return; 
      }
      String sql = "insert into plogin values('"+usr+"','"+gp+"');";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Congratulations!!\nYou are successfully registered!!");
            String insert = "INSERT INTO airmed.userdetails VALUES('"+usr+"','"+name+"','"+email+"','"+city+"','"+state+"','"+pincode+"','"+phoneno+"','"+count+"');";
stmt1.executeUpdate(insert);
        


            patientlogin ob = new patientlogin();
            this.setVisible(false);
            ob.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(patientlogin.class.getName()).log(Level.SEVERE, null, ex);
        }   
      // TODO add your handling code here:
    }//GEN-LAST:event_SignupMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
this.setState(this.ICONIFIED);          // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void ppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppMouseClicked
    patientlogin ob = new patientlogin();
this.setVisible(false);
ob.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_ppMouseClicked

    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
Aboutus ob = new Aboutus();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_aboutusMouseClicked

    private void dpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpMouseClicked
 doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_dpMouseClicked

    /**
     * @param args the command line arguments
     */public static boolean isValidEmailAddress(String email) {
   boolean result = true;
   try {
      InternetAddress emailAddr = new InternetAddress(email);
      emailAddr.validate();
   } catch (AddressException ex) {
      result = false;
   }
   return result;
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patientsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patientsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patientsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patientsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patientsignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel Signup;
    private javax.swing.JLabel aboutus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel close;
    private javax.swing.JLabel dp;
    private javax.swing.JLabel home;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel pp;
    // End of variables declaration//GEN-END:variables
}
