/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
/**
 *
 * @author win-8
 */
public class patientlogin extends javax.swing.JFrame {
    public static String username = "";
    public static String naam = "";
    public static String Email = "";
    public static String City = "";
    public static String State = "";
    public static String Pin = "";
    public static String Phone = "";
    //public static String password = "";
    /**
     * Creates new form patientlogin
     */
    public patientlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        designpass = new javax.swing.JPasswordField();
        userid = new javax.swing.JTextField();
        Close = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        doctorportal = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        aboutus = new javax.swing.JLabel();
        patientsportal = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        newuser = new javax.swing.JLabel();
        BMI = new javax.swing.JLabel();
        Forget = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        designpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(designpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 250, -1));

        userid.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 250, -1));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 30));

        doctorportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctorportal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorportalMouseClicked(evt);
            }
        });
        getContentPane().add(doctorportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 230, 30));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        aboutus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
        });
        getContentPane().add(aboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, 130, 30));

        patientsportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientsportal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientsportalMouseClicked(evt);
            }
        });
        getContentPane().add(patientsportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 240, 30));

        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 160, 50));

        newuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserMouseClicked(evt);
            }
        });
        getContentPane().add(newuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 290, 30));

        BMI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMIMouseClicked(evt);
            }
        });
        getContentPane().add(BMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 600, 70, 80));

        Forget.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Forget.setForeground(new java.awt.Color(0, 51, 255));
        Forget.setText("Forgot Password?");
        Forget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetMouseClicked(evt);
            }
        });
        getContentPane().add(Forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/userlogin.jpg"))); // NOI18N
        BG.setText("Forgot Password");
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        String s;
   
    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);//        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void doctorportalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorportalMouseClicked
doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);//        // TODO add your handling code here:
    }//GEN-LAST:event_doctorportalMouseClicked

    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
Aboutus ob = new Aboutus();
this.setVisible(false);
ob.setVisible(true);//        // TODO add your handling code here:
    }//GEN-LAST:event_aboutusMouseClicked

    private void BMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMIMouseClicked
Predict ob = new Predict();
this.setVisible(false);
ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BMIMouseClicked

    private void patientsportalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientsportalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_patientsportalMouseClicked

    private void newuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserMouseClicked
Patientsignup ob = new Patientsignup();
this.setVisible(false);
ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_newuserMouseClicked

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
      try {
          username = userid.getText();
          char[] pa = designpass.getPassword();
          String password = new String(pa);
          if(username.length()==0||password.length()==0)
        {
            //JOptionPane.showMessageDialog(this, "Necessary fields are left empty/nPlease re-enter.");
            //return;
            JOptionPane.showMessageDialog(this, "Necessary fields are left empty\nPlease re-enter.", "Warning...",
        JOptionPane.WARNING_MESSAGE);
            return;
        }
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airmed?useSSL=false","root", "aman");
            Statement stmt = con.createStatement();
            
            
            
            
            String stm = "SELECT COUNT(*) AS total from airmed.plogin WHERE User_id = '" + username + "'";
    
            ResultSet rs1;
            int counter = 0;
    try {
        Statement stmt1=con.createStatement();
        rs1 = stmt1.executeQuery(stm);
        while(rs1.next()){
    counter = rs1.getInt("total");
    }
    } catch (SQLException ex) {
        Logger.getLogger(Forgetpatient.class.getName()).log(Level.SEVERE, null, ex);
    }
    if(counter==0)
    {
        JOptionPane.showMessageDialog(this, "User doesn't exist...");
        userid.setText("");
        designpass.setText("");
        return;
    }
            
            //String sql = "insert into login values('"+usr+"','"+gp+"');";
            //stmt.executeUpdate(sql);
            ResultSet rs = stmt.executeQuery("Select Password from plogin where User_id = '"+username+"';");
            while(rs.next())
            {
               String dp = AESCrypt.decrypt(rs.getString("Password"));
               if(dp.equals(password))
               {
                  
                  
                  
                   
        Statement stmt3 = con.createStatement();
        ResultSet rs5;
        //String naam = "";
        //System.out.println(username);
         rs5 = stmt3.executeQuery("Select Name from airmed.userdetails where User_ID = '"+username+"';");
        while(rs5.next())
            {
               naam  = rs5.getString("Name");
            }
        //System.out.println(naam);
        ///ob.Name.setText(naam);
           
        ResultSet rs6 = stmt3.executeQuery("Select E_mail from airmed.userdetails where User_ID = '"+username+"';");
        while(rs6.next())
            {
               Email  = rs6.getString("E_mail");
            }
        
        ResultSet rs7 = stmt3.executeQuery("Select City from airmed.userdetails where User_ID = '"+username+"';");
        while(rs7.next())
            {
               City  = rs7.getString("City");
            }
        
        ResultSet rs8 = stmt3.executeQuery("Select State from airmed.userdetails where User_ID = '"+username+"';");
        while(rs8.next())
            {
               State  = rs8.getString("State");
            }
        
        ResultSet rs9 = stmt3.executeQuery("Select Pin from airmed.userdetails where User_ID = '"+username+"';");
        while(rs9.next())
            {
               Pin  = rs9.getString("Pin");
            }
        
        ResultSet rs10 = stmt3.executeQuery("Select Phone from airmed.userdetails where User_ID = '"+username+"';");
        while(rs10.next())
            {
               Phone  = rs10.getString("Phone");
            }
        
        
        
        
        
        
        
        
        
        
        
         Userfrontpage ob = new Userfrontpage();          
                   
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  this.setVisible(false);
                  ob.setVisible(true);
//View main menu  
return;
               }
               
            }
            //JOptionPane.showMessageDialog(this, "Incorrect ID or Password\nPlease re-enter");
            JOptionPane optionPane = new JOptionPane("Error Message", JOptionPane.ERROR_MESSAGE);    
JDialog dialog = optionPane.createDialog("User ID or password is incorrect!");
dialog.setAlwaysOnTop(true);
dialog.setVisible(true);
return;

        } catch (SQLException ex) {
            Logger.getLogger(patientlogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(patientlogin.class.getName()).log(Level.SEVERE, null, ex);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_LoginMouseClicked

    private void ForgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetMouseClicked
Forgetpatient ob = new Forgetpatient();
this.setVisible(false);
ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_ForgetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BMI;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Forget;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel aboutus;
    private javax.swing.JPasswordField designpass;
    private javax.swing.JLabel doctorportal;
    private javax.swing.JLabel newuser;
    private javax.swing.JLabel patientsportal;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
