/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import matrix.NoSquareException;
import mlr.*;
/**
 *
 * @author win-8
 */
public class Predict extends javax.swing.JFrame {
    public static int age=0;
    public static int gender=0;
    public static int dietscore = 0; 
    /**
     * Creates new form Predict
     */
    public Predict() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group = new javax.swing.ButtonGroup();
        Male = new javax.swing.JRadioButton();
        Age = new javax.swing.JTextField();
        Female = new javax.swing.JRadioButton();
        Minimize = new javax.swing.JLabel();
        Dietscore = new javax.swing.JTextField();
        Close = new javax.swing.JLabel();
        Submit = new javax.swing.JLabel();
        docportal = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        patientportal = new javax.swing.JLabel();
        Help = new javax.swing.JLabel();
        aboutus = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Group.add(Male);
        Male.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 423, -1, -1));

        Age.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 310, 30));

        Group.add(Female);
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 423, -1, -1));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        Dietscore.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        getContentPane().add(Dietscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 320, 30));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        Submit.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 624, 80, 80));

        docportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        docportal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docportalMouseClicked(evt);
            }
        });
        getContentPane().add(docportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 230, 30));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 30));

        patientportal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientportal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientportalMouseClicked(evt);
            }
        });
        getContentPane().add(patientportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 240, 30));

        Help.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Help.setForeground(new java.awt.Color(0, 102, 255));
        Help.setText("Help?");
        Help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpMouseClicked(evt);
            }
        });
        getContentPane().add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, -1, -1));

        aboutus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
        });
        getContentPane().add(aboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, 130, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/bmi1.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        String ag = Age.getText();
        String dietscor = Dietscore.getText();
        if(Male.isSelected())
            gender = 1;
        else
            gender = 0;
        if(ag.length()==0||dietscor.length()==0||(Male.isSelected()==false&&Female.isSelected()==false))
        {
            JOptionPane.showMessageDialog(this, "Necessary fields are left empty/nPlease re-enter.");
            return;
        }
        age = Integer.parseInt(ag);
        if(age>130||age<1)
        {
            JOptionPane.showMessageDialog(this, "Invalid Age. Age cannot be greater than 130 or less than 1.\nPlease re-enter.", "Warning...",
        JOptionPane.WARNING_MESSAGE);
            Age.setText("");
            return;
        }
        dietscore = Integer.parseInt(dietscor);
        if(dietscore>10||dietscore<1)
        {
            JOptionPane.showMessageDialog(this, "Invalid Dietscore. Dietscore cannot be greater than 10 or less than 1.\nPlease re-enter.", "Warning...",
        JOptionPane.WARNING_MESSAGE);
            Dietscore.setText("");
            return;
        }
        String ar[] = new String[2];
        ar[0]="Aman";
        ar[1]="Fixyou";
        try {
            BMI.main(ar);
        } catch (SQLException ex) {
            Logger.getLogger(Predict.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSquareException ex) {
            Logger.getLogger(Predict.class.getName()).log(Level.SEVERE, null, ex);
        }
        double ans = BMI.finalans;
        bmipredicted ob = new bmipredicted();
        String a = String.format( "%.2f", ans);
        ob.bmifinal.setText(a);
        this.setVisible(false);
        ob.setVisible(true);
        
            
        
    // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void patientportalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientportalMouseClicked
patientlogin ob = new patientlogin();
this.setVisible(false);
ob.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_patientportalMouseClicked

    private void docportalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docportalMouseClicked
doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_docportalMouseClicked

    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
Aboutus ob = new Aboutus();
this.setVisible(false);
ob.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_aboutusMouseClicked

    private void HelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseClicked
        String str = "The CSIRO Healthy Diet Score  is a scientifically validated survey, \n It assesses a person’s diet against Australia’s healthy eating guidelines, \n It provides a single dietary quality score on a 10-point scale.";
        JOptionPane.showMessageDialog(this, str);        // TODO add your handling code here:
    }//GEN-LAST:event_HelpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Predict.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Predict.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Predict.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Predict.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Predict().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Close;
    private javax.swing.JTextField Dietscore;
    private javax.swing.JRadioButton Female;
    private javax.swing.ButtonGroup Group;
    private javax.swing.JLabel Help;
    private javax.swing.JLabel Home;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel Minimize;
    public javax.swing.JLabel Submit;
    private javax.swing.JLabel aboutus;
    private javax.swing.JLabel docportal;
    private javax.swing.JLabel patientportal;
    // End of variables declaration//GEN-END:variables
}
