/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author win-8
 */
public class prediction1 extends javax.swing.JFrame {

    /**
     * Creates new form prediction1
     */
    public static String disease = "";
    public static String a = "";
    public prediction1() {
        initComponents();
    }
boolean sym[] = new boolean[32];
    int c = 0;
    String arr[] = new String[32];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        Close = new javax.swing.JLabel();
        Submit = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Bookapp = new javax.swing.JLabel();
        chat = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setText("Recurring_fever");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jCheckBox2.setText("Sweating");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        jCheckBox3.setText("Diarrhea");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jCheckBox5.setText("Fatigue");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, -1, -1));

        jCheckBox14.setText("Abdominal_cramps");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, -1, -1));

        jCheckBox8.setText("Nausea");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        jCheckBox4.setText("Rapid_weight_loss");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, -1, -1));

        jCheckBox18.setText("Blood_in_vomit");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        jCheckBox20.setText("Back_pain");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, -1, 20));

        jCheckBox11.setText("Weight_loss");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        jCheckBox21.setText("Chills");
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        jCheckBox27.setText("Blood_in_cough");
        jCheckBox27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox27ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, -1, -1));

        jCheckBox30.setText("Bleeding_from_rectum");
        jCheckBox30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox30ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 570, -1, -1));

        jCheckBox19.setText("Rashes");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        jCheckBox29.setText("Lots_of_appetite");
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox29ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, -1, -1));

        jCheckBox13.setText("Dehydration");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, -1));

        jCheckBox28.setText("Cough_over_3_weeks");
        jCheckBox28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox28ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, -1, -1));

        jCheckBox6.setText("Severe_headache");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jCheckBox23.setText("Cough");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, -1));

        jCheckBox25.setText("Body_pain");
        jCheckBox25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox25ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, -1, -1));

        jCheckBox15.setText("Pain_in_joints");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, -1, -1));

        jCheckBox9.setText("Bloody_stools");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        jCheckBox10.setText("Vomiting");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, -1, -1));

        jCheckBox17.setText("Fast_pulse");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        jCheckBox12.setText("Low_blood_pressure");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        jCheckBox7.setText("Loose_stools");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jCheckBox24.setText("Sore_throat");
        jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox24ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, -1, -1));

        jCheckBox26.setText("Chest_pain");
        jCheckBox26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox26ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, -1));

        jCheckBox16.setText("Pain_in_eyes");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        jCheckBox22.setText("Running_nose");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        jCheckBox31.setText("Stomach_pain");
        jCheckBox31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox31ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, -1, -1));

        jCheckBox32.setText("Fever");
        jCheckBox32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox32ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, -1, -1));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 80, 80));

        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, 20));

        Bookapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bookapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookappMouseClicked(evt);
            }
        });
        getContentPane().add(Bookapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 270, 20));

        chat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatMouseClicked(evt);
            }
        });
        getContentPane().add(chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 270, 20));

        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 190, 70, 20));

        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });
        getContentPane().add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 110, 20));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/PREDICTION1.jpg"))); // NOI18N
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        sym[0] = jCheckBox1.isEnabled();
        arr[0] = jCheckBox1.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        sym[1] = jCheckBox2.isEnabled();
        arr[1] = jCheckBox2.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        sym[2] = jCheckBox3.isEnabled();
        arr[2] = jCheckBox3.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        sym[3] = jCheckBox4.isEnabled();
        arr[3] = jCheckBox4.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        sym[4] = jCheckBox5.isEnabled();
        arr[4] = jCheckBox5.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        sym[5] = jCheckBox6.isEnabled();
        arr[5] = jCheckBox6.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        sym[6] = jCheckBox7.isEnabled();
        arr[6] = jCheckBox7.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        sym[7] = jCheckBox8.isEnabled();
        arr[7] = jCheckBox8.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        sym[8] = jCheckBox9.isEnabled();
        arr[8] = jCheckBox9.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
       sym[9] = jCheckBox10.isEnabled();
        arr[9] = jCheckBox10.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        sym[10] = jCheckBox11.isEnabled();
        arr[10] = jCheckBox11.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        sym[11] = jCheckBox12.isEnabled();
        arr[11] = jCheckBox12.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        sym[12] = jCheckBox13.isEnabled();
        arr[12] = jCheckBox13.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        sym[13] = jCheckBox14.isEnabled();
        arr[13] = jCheckBox14.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        sym[14] = jCheckBox15.isEnabled();
        arr[14] = jCheckBox15.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        sym[15] = jCheckBox16.isEnabled();
        arr[15] = jCheckBox16.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        sym[16] = jCheckBox17.isEnabled();
        arr[16] = jCheckBox17.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
       sym[17] = jCheckBox18.isEnabled();
        arr[17] = jCheckBox18.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        sym[18] = jCheckBox19.isEnabled();
        arr[18] = jCheckBox19.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        sym[19] = jCheckBox20.isEnabled();
        arr[19] = jCheckBox20.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        sym[20] = jCheckBox21.isEnabled();
        arr[20] = jCheckBox21.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
       sym[21] = jCheckBox22.isEnabled();
        arr[21] = jCheckBox22.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        sym[22] = jCheckBox23.isEnabled();
        arr[22] = jCheckBox23.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox24ActionPerformed
        sym[23] = jCheckBox24.isEnabled();
        arr[23] = jCheckBox24.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox24ActionPerformed

    private void jCheckBox25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox25ActionPerformed
        sym[24] = jCheckBox25.isEnabled();
        arr[24] = jCheckBox25.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox25ActionPerformed

    private void jCheckBox26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox26ActionPerformed
        sym[25] = jCheckBox26.isEnabled();
        arr[25] = jCheckBox26.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox26ActionPerformed

    private void jCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox27ActionPerformed
        sym[26] = jCheckBox27.isEnabled();
        arr[26] = jCheckBox27.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox27ActionPerformed

    private void jCheckBox28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox28ActionPerformed
       sym[27] = jCheckBox28.isEnabled();
        arr[27] = jCheckBox28.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox28ActionPerformed

    private void jCheckBox29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox29ActionPerformed
       sym[28] = jCheckBox29.isEnabled();
        arr[28] = jCheckBox29.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox29ActionPerformed

    private void jCheckBox30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox30ActionPerformed
       sym[29] = jCheckBox30.isEnabled();
        arr[29] = jCheckBox30.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox30ActionPerformed

    private void jCheckBox31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox31ActionPerformed
        sym[30] = jCheckBox31.isEnabled();
        arr[30] = jCheckBox31.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox31ActionPerformed

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        int i = 0;
        //jProgressBar1.setIndeterminate(true);
        /*Cursor cursor = Cursor.getDefaultCursor();
     //change cursor appearance to HAND_CURSOR when the mouse pointed on images
     cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR); 
     setCursor(cursor);*/
        for(i=0;i<sym.length;i++)
            { 
                if(sym[i] == true)
                {
                    c++;
                }
            }
        if(c==0)
        {
            JOptionPane.showMessageDialog(this, "You haven't selected any symptoms.\n Please select some.", "Warning...",
        JOptionPane.WARNING_MESSAGE);
            return;
        }
            String arrFinal[] = new String[c];
            int j=0;
            for(i=0;i<sym.length;i++)
            {
                if(sym[i] == true)
                {
                    arrFinal[j] = arr[i];
                    j++;
                }
            }
           
        try {
            double probability = 0;      
            Bayessian.main(arrFinal);
            probability = Bayessian.prob;
            disease = "AIDS";
            amebiasis.main(arrFinal);
            if(probability<amebiasis.pamebiasis)
            {
                probability=amebiasis.pamebiasis;
                disease = "Amebiasis";
            }
            cholera.main(arrFinal);
            if(probability<cholera.pcholera)
            {
                probability=cholera.pcholera;
                disease = "Cholera";
            }
            dengue.main(arrFinal);
            if(probability<dengue.pdengue)
            {
                probability=dengue.pdengue;
                disease = "Dengue";
            }
            ebola.main(arrFinal);
            if(probability<ebola.pebola)
            {
                probability=ebola.pebola;
                disease = "Ebola";
            }
            malaria.main(arrFinal);
            if(probability<malaria.pmalaria)
            {
                probability=malaria.pmalaria;
                disease = "Malaria";
            }
            smallpox.main(arrFinal);
            if(probability<smallpox.psmallpox)
            {
                probability=smallpox.psmallpox;
                disease = "Smallpox";
            }
            swineflu.main(arrFinal);
            if(probability<swineflu.pswineflu)
            {
                probability=swineflu.pswineflu;
                disease = "Swineflu";
            }
            tuberculosis.main(arrFinal);
            if(probability<tuberculosis.ptuberculosis)
            {
                probability=tuberculosis.ptuberculosis;
                disease = "Tuberculosis";
            }
            typhoid.main(arrFinal);
            if(probability<typhoid.ptyphoid)
            {
                probability=typhoid.ptyphoid;
                disease = "Typhoid";
            }
            probability*=100;
            a = String.format( "%.2f", probability);
            //System.out.println(probability+"\n"+disease);
            
    /*ImageIcon loading = new ImageIcon("ajax-loader.gif");
    this.add(new JLabel("loading... ", loading, JLabel.CENTER));*/
            prediction2 ob = new prediction2();
            ob.Disease.setText(disease);
            ob.percentage.setText(a);
           // String m = ".";
         
    
            this.setVisible(false);
            //
            //String temp[]={"Aman"};
            //animate.main(temp);
            //Thread.sleep(5000);
            ob.setVisible(true);
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(prediction1.class.getName()).log(Level.SEVERE, null, ex);
        } /*catch (InterruptedException ex) {
            Logger.getLogger(prediction1.class.getName()).log(Level.SEVERE, null, ex);
        } */
    }//GEN-LAST:event_SubmitMouseClicked

    private void jCheckBox32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox32ActionPerformed
        sym[31] = jCheckBox32.isEnabled();
        arr[31] = jCheckBox32.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox32ActionPerformed

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void BookappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookappMouseClicked
appointment1 ob = new appointment1();
this.setVisible(false);
ob.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_BookappMouseClicked

    private void chatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatMouseClicked
try
{
        userchat ob = new userchat();
this.setVisible(false);
ob.setVisible(true); 
}
catch(Exception e)
{}// TODO add your handling code here:
    }//GEN-LAST:event_chatMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
patientlogin ob = new patientlogin();
this.setVisible(false);
ob.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
userprofile ob = new userprofile();
this.setVisible(false);
ob.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_ProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prediction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prediction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prediction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prediction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prediction1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Bookapp;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel Submit;
    private javax.swing.JLabel chat;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    // End of variables declaration//GEN-END:variables
}
