/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

import static air.med.Forgetpatient.id;
import static air.med.patientlogin.Email;
import static air.med.patientlogin.username;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author win-8
 */
public class seemessage extends javax.swing.JFrame {

    /**
     * Creates new form seemessage
     */
    public seemessage() throws SQLException {
        initComponents();
        
        
         
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        String s;
        
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airmed?useSSL=false","root", "aman");
            Statement stmt = con.createStatement();
            
            
            
            
            String stm = "SELECT COUNT(*) AS total from airmed.doctordetails";
            ResultSet rs1;
            int counter = 0;
    try {
        Statement stmt1=con.createStatement();
        rs1 = stmt1.executeQuery(stm);
        while(rs1.next()){
    counter = rs1.getInt("total");
    }
    } catch (SQLException ex) {
        Logger.getLogger(Forgetpatient.class.getName()).log(Level.SEVERE, null, ex);
    }
    String doclist[] = new String[counter];
    Statement stmt2=con.createStatement();
    int i = 0;
    ResultSet rs6 = stmt2.executeQuery("Select Name from airmed.doctordetails");
        while(rs6.next())
            {
               doclist[i]  = rs6.getString("Name");
               i++;
            }
        
        
        
        
        //String[] comboBoxArray = {"iljjku","iujgum2","ljhlem3"};


//create JComboBox and assign it to the comboBox
jComboBox1.removeAllItems();
for(int j=0;j<counter;j++)
{
    jComboBox1.addItem(doclist[j]);
}

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        Ticker = new javax.swing.JLabel();
        Chat = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        predict = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Myriad Pro", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 370, 230));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 370, 30));

        Ticker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ticker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TickerMouseClicked(evt);
            }
        });
        getContentPane().add(Ticker, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 674, 80, 80));

        Chat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChatMouseClicked(evt);
            }
        });
        getContentPane().add(Chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 270, 30));

        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 190, 80, 20));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });
        getContentPane().add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 110, 20));

        predict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        predict.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                predictMouseClicked(evt);
            }
        });
        getContentPane().add(predict, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 230, 30));

        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 270, 30));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/PATIENTMESAGE.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TickerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TickerMouseClicked
String sValue = (String)jComboBox1.getSelectedItem();
//System.out.println(sValue);
Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airmed?useSSL=false","root", "aman");
        } catch (SQLException ex) {
            Logger.getLogger(seemessage.class.getName()).log(Level.SEVERE, null, ex);
        }
String ide = null;
     Statement stmt3;    
        try {
            stmt3 = con.createStatement();
         
   ResultSet rs6 = stmt3.executeQuery("Select doc_ID from airmed.doctordetails where Name = '"+sValue+"';");
        while(rs6.next())
            {
               ide  = rs6.getString("doc_ID");
            }  
        }
        catch (SQLException ex) {
            Logger.getLogger(seemessage.class.getName()).log(Level.SEVERE, null, ex);
        }
        ide+=".txt";
        //System.out.println(ide);
        try
        {
            File f = new File("C:/Aman",ide);
            
FileReader reader = new FileReader(f);
BufferedReader br = new BufferedReader(reader);
jTextArea1.read( br, null );
br.close();
        }
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, "No message to show from selected doctor...");
}      // TODO add your handling code here:
    }//GEN-LAST:event_TickerMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
appointment1 ob = new appointment1();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void predictMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_predictMouseClicked
prediction1 ob = new prediction1();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_predictMouseClicked

    private void ChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChatMouseClicked
try{
        userchat ob = new userchat();
this.setVisible(false);
ob.setVisible(true);  
}
catch(Exception e)
{
    
}// TODO add your handling code here:
    }//GEN-LAST:event_ChatMouseClicked

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
userprofile ob = new userprofile();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
doctorone ob = new doctorone();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seemessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seemessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seemessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seemessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new seemessage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(seemessage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Chat;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel Ticker;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel predict;
    // End of variables declaration//GEN-END:variables
}
