/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air.med;

import static air.med.patientlogin.Email;
import static air.med.patientlogin.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author win-8
 * 
 */
class asyncCChat extends Thread{
    //public static String sValue="";
    //private static Server server;
    private static Client client;
    
    public asyncCChat(Client c){
        client =c;
    }
    /*public void startServer(Server s){
        server = s;
    }*/
    public void run(){
        client.startRunning();
    }
}

class asyncSChat extends Thread{
    private static Server server;
    //private static Client client;
    
    /*public void startClient(Client c){
        client =c;
    }*/
    public asyncSChat(Server s){
        server = s;
    }
    public void run(){
        server.startRunning();
    }
}
public class userchat extends javax.swing.JFrame {

    /**
     * Creates new form userchat
     */
    public userchat() throws SQLException {
        initComponents();
        
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        String s;
        
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airmed?useSSL=false","root", "aman");
            Statement stmt = con.createStatement();
            
            
            
            
            String stm = "SELECT COUNT(*) AS total from airmed.doctordetails";
            ResultSet rs1;
            int counter = 0;
    try {
        Statement stmt1=con.createStatement();
        rs1 = stmt1.executeQuery(stm);
        while(rs1.next()){
    counter = rs1.getInt("total");
    }
    } catch (SQLException ex) {
        Logger.getLogger(Forgetpatient.class.getName()).log(Level.SEVERE, null, ex);
    }
    String doclist[] = new String[counter];
    Statement stmt2=con.createStatement();
    int i = 0;
    ResultSet rs6 = stmt2.executeQuery("Select Name from airmed.doctordetails");
        while(rs6.next())
            {
               doclist[i]  = rs6.getString("Name");
               i++;
            }
        
        
        
        
        //String[] comboBoxArray = {"iljjku","iujgum2","ljhlem3"};


//create JComboBox and assign it to the comboBox
jComboBox1.removeAllItems();
for(int j=0;j<counter;j++)
{
    jComboBox1.addItem(doclist[j]);
}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Chat = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Home = new javax.swing.JLabel();
        bookapp = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        predict = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChatMouseClicked(evt);
            }
        });
        getContentPane().add(Chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 680, 80, 80));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 170, 30));

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, 20));

        bookapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookappMouseClicked(evt);
            }
        });
        getContentPane().add(bookapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 270, 20));

        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 110, 20));

        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 30, 40));

        predict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        predict.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                predictMouseClicked(evt);
            }
        });
        getContentPane().add(predict, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 230, 30));

        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 190, 80, 20));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 40));

        Message.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Message.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MessageMouseClicked(evt);
            }
        });
        getContentPane().add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, 110, 70));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air/med/USERCHAT.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChatMouseClicked

        String sValue = (String)jComboBox1.getSelectedItem();
        
        try
{
        Server server = new Server(sValue);
        asyncSChat as = new asyncSChat(server);
        as.start();
        Client client = new Client("127.0.0.1");
        //client.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        asyncCChat ac = new asyncCChat(client);
        ac.start();
        System.out.print(ac.isAlive());   
}
catch(Exception e )
{
    JOptionPane.showMessageDialog(this, "Address already in use. We are actually short of ports:P.\n You will be redirected back to your home page.\n Sorry for the inconvenience.", "Warning...",
        JOptionPane.WARNING_MESSAGE);
    Userfrontpage ob = new Userfrontpage();
    this.setVisible(false);
    ob.setVisible(true);
            return;
            
}// TODO add your handling code here:
    }//GEN-LAST:event_ChatMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
Home ob = new Home();
this.setVisible(false);
ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void bookappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookappMouseClicked
   appointment1 ob = new appointment1();
this.setVisible(false);
ob.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_bookappMouseClicked

    private void predictMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_predictMouseClicked
prediction1 ob = new prediction1();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_predictMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
userprofile ob = new userprofile();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_profileMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
patientlogin ob = new patientlogin();
this.setVisible(false);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked

    private void MessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MessageMouseClicked
try{
        seemessage ob = new seemessage();
      
this.setVisible(false);
ob.setVisible(true);
}
catch(Exception e)
{
    
}// TODO add your handling code here:
    }//GEN-LAST:event_MessageMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
this.setState(this.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new userchat().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(userchat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Chat;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel bookapp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel predict;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
